import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface Budget {
  title: string;
  amount: number;
  totalSpent: number;
  remaining: number;
  percentage: number;
  category: string;
  month: number;
  year: number;
}

interface Expense {
  title: string;
  amount: number;
  category: string;
  month: number;
  year: number;
}

const MONTHS = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
];

export function exportToPDF({
  budgets,
  expenses,
  month,
  year,
  userName,
}: {
  budgets: Budget[];
  expenses: Expense[];
  month: number | "all";
  year: number;
  userName?: string;
}) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // ── Header ──
  doc.setFillColor(79, 70, 229); // indigo
  doc.rect(0, 0, pageWidth, 30, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Spendly — Financial Report", 14, 18);

  // Period & user info
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  const periodLabel =
    month === "all"
      ? `Full Year ${year}`
      : `${MONTHS[Number(month) - 1]} ${year}`;
  doc.text(`Period: ${periodLabel}`, 14, 26);
  if (userName)
    doc.text(`User: ${userName}`, pageWidth - 14, 26, { align: "right" });

  // ── Summary Box ──
  const totalBudget = budgets.reduce((s, b) => s + b.amount, 0);
  const totalSpent = budgets.reduce((s, b) => s + b.totalSpent, 0);
  const totalRemaining = totalBudget - totalSpent;

  doc.setTextColor(0, 0, 0);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Summary", 14, 42);

  doc.setDrawColor(229, 231, 235);
  doc.setFillColor(249, 250, 251);
  doc.roundedRect(14, 46, pageWidth - 28, 22, 3, 3, "FD");

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(107, 114, 128);
  doc.text("Total Budget", 20, 54);
  doc.text("Total Spent", 80, 54);
  doc.text("Remaining", 140, 54);

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(79, 70, 229);
  doc.text(`৳${totalBudget.toLocaleString()}`, 20, 63);
  doc.setTextColor(239, 68, 68);
  doc.text(`৳${totalSpent.toLocaleString()}`, 80, 63);
  doc.setTextColor(
    totalRemaining < 0 ? 239 : 16,
    totalRemaining < 0 ? 68 : 185,
    totalRemaining < 0 ? 68 : 129,
  );
  doc.text(`৳${totalRemaining.toLocaleString()}`, 140, 63);

  // ── Budget Table ──
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Budget Summary", 14, 80);

  autoTable(doc, {
    startY: 84,
    head: [
      [
        "Title",
        "Category",
        "Budget (৳)",
        "Spent (৳)",
        "Remaining (৳)",
        "Status",
      ],
    ],
    body: budgets.map((b) => [
      b.title,
      b.category || "Other",
      b.amount.toLocaleString(),
      b.totalSpent.toLocaleString(),
      b.remaining.toLocaleString(),
      b.percentage >= 100
        ? "🔥 Exceeded"
        : b.percentage >= 80
          ? "⚠ Warning"
          : "✔ Safe",
    ]),
    headStyles: { fillColor: [79, 70, 229], textColor: 255, fontSize: 9 },
    bodyStyles: { fontSize: 9 },
    alternateRowStyles: { fillColor: [249, 250, 251] },
    columnStyles: {
      2: { halign: "right" },
      3: { halign: "right" },
      4: { halign: "right" },
    },
  });

  // ── Expense Table ──
  const finalY = (doc as any).lastAutoTable.finalY + 12;

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Expense List", 14, finalY);

  autoTable(doc, {
    startY: finalY + 4,
    head: [["Title", "Category", "Amount (৳)", "Month", "Year"]],
    body: expenses.map((e) => [
      e.title,
      e.category || "Other",
      e.amount.toLocaleString(),
      MONTHS[e.month - 1],
      e.year,
    ]),
    headStyles: { fillColor: [79, 70, 229], textColor: 255, fontSize: 9 },
    bodyStyles: { fontSize: 9 },
    alternateRowStyles: { fillColor: [249, 250, 251] },
    columnStyles: {
      2: { halign: "right" },
    },
  });

  // ── Footer ──
  doc.setFontSize(8);
  doc.setTextColor(156, 163, 175);
  doc.text(
    `Generated by Spendly • ${new Date().toLocaleDateString()}`,
    pageWidth / 2,
    doc.internal.pageSize.getHeight() - 8,
    { align: "center" },
  );

  // ── Save ──
  const fileName =
    month === "all"
      ? `spendly-report-${year}.pdf`
      : `spendly-report-${MONTHS[Number(month) - 1]}-${year}.pdf`;

  doc.save(fileName);
}
